### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by fmeloSP** [bschlintz/spfx-googleanalytics-tenant#1]
I followed the install and uploaded the package to the app cat. i modified the ua number in the tenantwide list, but it only shows up in the app cat.
should it show up everywhere else? how do i know its working?

**Comment by bschlintz** [comment]
Tenant wide extensions can take a few hours to propagate the very first time they're used in a tenant. If you didn't specify a site template filter, then the extension should load on all modern pages tenant-wide. 

Easiest way to tell if its working is to check the analytics portal. You can also use the [SPFx developer dashboard](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-developer-dashboard) to verify the SPFx extension is being loaded on a given modern page.
